#+title: Brief aan mijzelf
#+options: num:nil toc:nil
#+author: Josep Jesus Bigorra Algaba
#+email: jjbigorra@gmail.com
#+date: <2024-06-17 ma>
#+language: nl


Lieve Joe,

Jij en ik weten dat levend zijn pieken en dalen betekent.
Alles wat je heb meegemaakt heeft dit een volle, veelzijdige, maar gezellige bus.

In deze bus zitten heel veel Joe's: doelgerichte Joe, aan de kant duwen Joe, vechter, niet-empatisch, idealistisch, hoge verwachtingen, hoge lat, inspirerend, hulpzaam, creatief, chill, zal goed komen, etc.

Het is waar, vaak staat gladiator Joe voorin de bus, vooral als iemand of iets in de weg zit van doelgerichte Joe. Vaak wurgt ie zijn weg en toont weinig empathie en emoties, terwijl het allemaal heel veel pijn doet.

En dus, dit maakt het moeilijk om behulpzaam, lief en chill zijn met anderen, terwijl je dat heel graag ook wil.

Laten we afspreken dat je een ambitieuze krijger blijft, omdat dat je zoveel heeft opgeleverd in het leven, en omdat uphill battles en battles in het algemeen jou zo motiveren.

Maar wees een inspirerend kracht, relativeer, blijf idealistisch, en "true to yourself", help anderen, neem meer tijd om de anderen te leren kennen, en hun emoties ook. Hoe moeilijk dat ook is.
